{{- if .Values.modelCache.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vllm-omni.fullname" . }}-model-cache
  labels:
    {{- include "vllm-omni.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.modelCache.accessMode }}
  {{- if .Values.modelCache.storageClassName }}
  storageClassName: {{ .Values.modelCache.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.modelCache.size }}
{{- end }}
