{{- if and .Values.huggingface.token (not .Values.huggingface.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm-omni.fullname" . }}-hf-token
  labels:
    {{- include "vllm-omni.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.huggingface.token | quote }}
{{- end }}
