apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portal.fullname" . }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITHUB_CLIENT_ID: {{ .Values.github.clientID | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.github.clientSecret | quote }}
  SESSION_SECRET: {{ .Values.sessionSecret | quote }}
