{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comfyui.fullname" . }}-auth
  labels:
    {{- include "comfyui.labels" . | nindent 4 }}
type: Opaque
data:
  htpasswd: {{ htpasswd .Values.auth.username .Values.auth.password | b64enc }}
  password: {{ .Values.auth.password | b64enc }}
{{- end }}
