{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "comfyui.fullname" . }}
  labels:
    {{- include "comfyui.labels" . | nindent 4 }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "comfyui.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.route.tls.termination }}
{{- end }}
